general {
    hide_cursor = true
}
background {
    monitor =
    path = @HOME@/.local/share/cpunk/source/backgrounds/Arcyx.png
    blur_passes = 1
}
input-field {
    monitor =
    size = 300, 52
    position = 0, -160
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgb(7f6e6e)
    inner_color = rgb(040303)
    font_color = rgb(ffffff)
    placeholder_text = Enter your password
    rounding = 0
    fade_on_empty = false
}
label {
    monitor =
    text = CPUNK // LOCKED
    font_family = JetBrains Mono
    font_size = 24
    color = rgb(ffffff)
    position = 0, -90
    halign = center
    valign = center
}
