theme = "cpunk"
close_when_open = true
hide_quick_activation = true
[providers]
default = ["desktopapplications"]
empty = ["desktopapplications"]
[placeholders]
default = { input = "CPUNK // Search applications", list = "No matching applications" }
